version: '3.1'

services:

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    links:
      - db
      - mailhog
    ports:
      - 8000:80
    env_file: env/local/wp.env
    volumes:
      - ./wp:/var/www/html/

  db:
    env_file: env/local/db.env
  # We use a mariadb image which supports both amd64 & arm64 architecture
    image: mariadb:10.6.4-focal
    # If you really want to use MySQL, uncomment the following line
    #image: mysql:8.0.27
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=somewordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    expose:
      - 3306
      - 33060
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    env_file: env/local/phpmyadmin.env
    links:
       - db
    ports:
      - 8080:80

  mailhog:
      image: mailhog/mailhog
      ports: 
        - 1025:1025 # smtp server
        - 8025:8025 # web ui
